[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "student-feedback-qnlp"
version = "0.0.0"

[tool.setuptools.packages.find]
where = ["src"]
